routes/web.php
<?php

use App\Http\Controllers\DomainController;
use App\Http\Controllers\EmailTemplateController;
use App\Http\Controllers\SMSTemplateController;
use App\Http\Controllers\WhatsappTemplateController;
use App\Http\Controllers\PermissionController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\SettingController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::view('admin/login', 'central.login')->name('central.login');

Route::prefix('user')->group(function () {
    Route::view('dashboard', 'central.dashboard')->name('dashboard');
    Route::get('profile', [ProfileController::class, 'index'])->name('user.profile');
    Route::patch('profile/update', [ProfileController::class, 'update']);
    Route::get('settings', [SettingController::class, 'index'])->name('user.setting');
    Route::patch('settings/update', [SettingController::class, 'update']);
	Route::view('notification', 'central.notification')->name('user.notification');
	Route::view('users', 'central.user')->name('users');
	Route::view('email-templates', 'central.email-template')->name('email-templates');
	Route::view('sms-templates', 'central.sms-template')->name('sms-templates');
	Route::view('whatsapp-templates', 'central.whatsapp-template')->name('whatsapp-templates');
	Route::get('domains/edit/{id}', [DomainController::class, 'edit'])->name('user.domains.edit');
	Route::get('email-template/edit/{id}', [EmailTemplateController::class, 'edit'])->name('user.email-template.edit');
	Route::post('email-template/delete/', [EmailTemplateController::class, 'destroy'])->name('user.email-template.delete');
	Route::get('sms-template/edit/{id}', [SMSTemplateController::class, 'edit'])->name('user.sms-template.edit');
	Route::post('sms-template/delete/', [SMSTemplateController::class, 'destroy'])->name('user.sms-template.delete');
	Route::get('whatsapp-template/edit/{id}', [WhatsappTemplateController::class, 'edit'])->name('user.whatsapp-template.edit');
	Route::post('whatsapp-template/delete/', [WhatsappTemplateController::class, 'destroy'])->name('user.whatsapp-template.delete');


    Route::resources([
        'domains'     => DomainController::class,
        'roles'       => RoleController::class,
        'permissions' => PermissionController::class,
		'email-template'=>EmailTemplateController::class,
		'sms-template'=>SMSTemplateController::class,
		'whatsapp-template'=>WhatsappTemplateController::class,

    ]);
});

resources/views/includes/common/menu/desktop.blade.php
<!-- Static sidebar for desktop -->
<div class="hidden lg:flex lg:flex-shrink-0">
    <div class="flex flex-col w-64">
        <!-- Sidebar component, swap this element with another sidebar if you like -->
        <div class="flex flex-col flex-grow bg-cyan-700 pt-5 pb-4 overflow-y-auto">
            <div class="flex items-center flex-shrink-0 px-4">
                <img class="h-8 w-auto" src="https://tailwindui.com/img/logos/easywire-logo-cyan-300-mark-white-text.svg" alt="Easywire logo">
            </div>

	        <nav class="mt-5 flex-1 flex flex-col divide-y divide-cyan-800 overflow-y-auto" aria-label="Sidebar">
	            @include('includes.common.menu.nav-links')
            </nav>
        </div>
    </div>
</div>

resources/views/includes/common/menu/mobile.blade.php
<div x-show="open" class="fixed inset-0 flex z-40 lg:hidden" role="dialog" aria-modal="true" style="display: none;">
    <div x-show="open"
         x-transition:enter="transition-opacity ease-linear duration-300"
         x-transition:enter-start="opacity-0"
         x-transition:enter-end="opacity-100"
         x-transition:leave="transition-opacity ease-linear duration-300"
         x-transition:leave-start="opacity-100"
         x-transition:leave-end="opacity-0"
         class="fixed inset-0 bg-gray-600 bg-opacity-75"
         aria-hidden="true">

    </div>

    <div x-show="open"
         x-transition:enter="transition ease-in-out duration-300 transform"
         x-transition:enter-start="-translate-x-full"
         x-transition:enter-end="translate-x-0"
         x-transition:leave="transition ease-in-out duration-300 transform"
         x-transition:leave-start="translate-x-0"
         x-transition:leave-end="-translate-x-full"
         class="relative flex-1 flex flex-col max-w-xs w-full pt-5 pb-4 bg-cyan-700">

        <div x-show="open"
             x-transition:enter="ease-in-out duration-300"
             x-transition:enter-start="opacity-0"
             x-transition:enter-end="opacity-100"
             x-transition:leave="ease-in-out duration-300"
             x-transition:leave-start="opacity-100"
             x-transition:leave-end="opacity-0"
             class="absolute top-0 right-0 -mr-12 pt-2">

            <button @click="open = false"
                    class="ml-1 flex items-center justify-center h-10 w-10 rounded-full focus:outline-none focus:ring-2 focus:ring-inset focus:ring-white">

                <span class="sr-only">Close sidebar</span>
                <x-heroicon-o-x class="h-6 w-6 text-white" />
            </button>

        </div>

        <div class="flex-shrink-0 flex items-center px-4">
            <img class="h-8 w-auto" src="https://tailwindui.com/img/logos/easywire-logo-cyan-300-mark-white-text.svg" alt="Easywire logo">
        </div>

	    <nav class="mt-5 flex-shrink-0 h-full divide-y divide-cyan-800 overflow-y-auto" aria-label="Sidebar">
	        @include('includes.common.menu.nav-links')
	    </nav>
    </div>

    <div class="flex-shrink-0 w-14" aria-hidden="true">
        <!-- Dummy element to force sidebar to shrink to fit close icon -->
    </div>
</div>

resources/views/includes/common/menu/nav-links.blade.php
<div class="px-2 space-y-1" x-data="{iswebhookapi: false}">
	<a href="{{ route('dashboard') }}" class="tw-admin-sidebar-nav-item {{ str_starts_with(Route::currentRouteName(), 'dashboard') ? 'active' : '' }}">
		<x-heroicon-o-home /> Home
	</a>

	<a href="{{ route('domains.index') }}" class="tw-admin-sidebar-nav-item {{ str_starts_with(Route::currentRouteName(), 'domains') ? 'active' : '' }}">
		<x-heroicon-o-globe-alt /> Domains
	</a>

	<a href="#" class="tw-admin-sidebar-nav-item">
		<x-heroicon-o-credit-card /> Billing
	</a>

	<a href="#" class="tw-admin-sidebar-nav-item">
		<x-heroicon-o-presentation-chart-line /> Reports
	</a>

	<a href="#" class="tw-admin-sidebar-nav-item">
		<x-heroicon-o-clock /> Logs
	</a>

	<a href="{{ route('roles.index') }}" class="tw-admin-sidebar-nav-item {{ str_starts_with(Route::currentRouteName(), 'roles') ? 'active' : '' }}">
		<x-heroicon-o-adjustments /> Roles
	</a>

	<a href="{{ route('users') }}" class="tw-admin-sidebar-nav-item {{ str_starts_with(Route::currentRouteName(), 'users') ? 'active' : '' }}">
		<x-heroicon-o-users /> Users
	</a>

	<a href="#" @click.prevent="iswebhookapi = !iswebhookapi" class="w-full tw-admin-sidebar-nav-item">
		<span class="flex items-center">
			<x-heroicon-o-document-text /> Templates </span>
		<span class="flex">
			<svg class="justify-end w-2 h-2" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
				<path x-show="!iswebhookapi" d="M9 5L16 12L9 19" stroke="currentColor" stroke-width="2"
							stroke-linecap="round" stroke-linejoin="round" style="display: none;"></path>
				<path x-show="iswebhookapi" d="M19 9L12 16L5 9" stroke="currentColor" stroke-width="2"
							stroke-linecap="round" stroke-linejoin="round"></path>
			</svg>
		</span>
	</a>
	<div x-show="iswebhookapi" class="bg-gray-0">
		<a href="{{ route('email-templates') }}" class="tw-sub-menu-link {{ str_starts_with(Route::currentRouteName(), 'email-templates') ? 'active' : '' }}">
			<span class="pr-2"><x-heroicon-o-mail class="w-4 h-4"/></span> Email
		</a>
		<a href="{{ route('sms-templates') }}" class="tw-sub-menu-link {{ str_starts_with(Route::currentRouteName(), 'sms-templates') ? 'active' : '' }}">
			<span class="pr-2"><x-heroicon-o-chat-alt class="w-4 h-4"/></span> SMS</a>
		<a href="{{ route('whatsapp-templates') }}" class="tw-sub-menu-link {{ str_starts_with(Route::currentRouteName(), 'whatsapp-templates') ? 'active' : '' }}">
			<span class="pr-2"><x-heroicon-o-chat class="w-4 h-4"/></span> WhatsApp</a>
	</div>
</div>

<div class="pt-6 mt-6">
	<div class="px-2 space-y-1">

		<a href="{{ route('user.notification') }}" class="tw-admin-sidebar-nav-item {{ str_starts_with(Route::currentRouteName(), 'user.notification') ? 'active' : '' }}">
			<x-heroicon-o-speakerphone /> Notifications
		</a>

		<a href="{{ route('user.setting') }}" class="tw-admin-sidebar-nav-item {{ str_starts_with(Route::currentRouteName(), 'user.setting') ? 'active' : '' }}">
			<x-heroicon-o-cog /> Settings
		</a>

		<a href="#" class="tw-admin-sidebar-nav-item" @click.prevent="document.getElementById('logout-form').submit()">
			<x-heroicon-o-logout /> Logout

			<form id="logout-form" method="POST" action="{{ route('logout') }}">
				@csrf
			</form>
		</a>
	</div>
</div>